# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchuser',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
